robotdb/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.urls import path
from . import views

admin.site.site_header = 'RobotDB administration'
admin.site.site_title = 'RobotDB'
admin.site.index_title = 'Robot administration'

urlpatterns = [
	path('admin/', admin.site.urls),
	path('', views.IndexView.as_view(), name = 'index'),
	path('accounts/', include('django.contrib.auth.urls')),
	path('articles/', views.ArticleListView.as_view(), name = 'articleList'),
	path('articles/add/', views.ArticleCreateView.as_view(), name = 'articleCreate'),
	path('articles/<int:articleID>/', views.ArticleDetailView.as_view(), name = 'articleDetail'),
	path('articles/<int:articleID>/edit/', views.ArticleUpdateView.as_view(), name = 'articleUpdate'),
	path('equipment/', views.EquipmentListView.as_view(), name = 'equipmentList'),
	path('equipment/add/', views.EquipmentCreateView.as_view(), name = 'equipmentCreate'),
	path('equipment/<int:equipmentID>/', views.EquipmentDetailView.as_view(), name = 'equipmentDetail'),
	path('equipment/<int:equipmentID>/edit/', views.EquipmentUpdateView.as_view(), name = 'equipmentUpdate'),
	path('projects/', views.ProjectListView.as_view(), name = 'projectList'),
	path('projects/add/', views.ProjectCreateView.as_view(), name = 'projectCreate'),
	path('projects/<int:projectID>/', views.ProjectDetailView.as_view(), name = 'projectDetail'),
	path('projects/<int:projectID>/edit/', views.ProjectUpdateView.as_view(), name = 'projectUpdate'),
	path('robots/', views.RobotListView.as_view(), name = 'robotList'),
	path('robots/add/', views.RobotCreateView.as_view(), name = 'robotCreate'),
	path('robots/<int:robotID>/', views.RobotDetailView.as_view(), name = 'robotDetail'),
	path('robots/<int:robotID>/edit/', views.RobotUpdateView.as_view(), name = 'robotUpdate'),
	path('skills/', views.SkillListView.as_view(), name = 'skillList'),
	path('skills/add/', views.SkillCreateView.as_view(), name = 'skillCreate'),
	path('skills/<int:skillID>/', views.SkillDetailView.as_view(), name = 'skillDetail'),
	path('skills/<int:skillID>/edit/', views.SkillUpdateView.as_view(), name = 'skillUpdate'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

robotdb/models/Application.py
from django.db import models
from django.urls import reverse

class Application(models.Model):
	ENHANCEMENT_VALUE_CHOICES = (
		(0, 'Not present'),
		(1, 'Physical'),
		(2, 'Non-physical'),
	)

	name = models.CharField(max_length = 100, unique = True)
	mobility = models.PositiveSmallIntegerField('Mobility enhancement', default = 0, choices = ENHANCEMENT_VALUE_CHOICES)
	selfreliantCare = models.PositiveSmallIntegerField('Selfreliant care', default = 0, choices = ENHANCEMENT_VALUE_CHOICES)
	interpersonalInteraction = models.PositiveSmallIntegerField('Interpersonal interaction', default = 0, choices = ENHANCEMENT_VALUE_CHOICES)
	other = models.PositiveSmallIntegerField('Other', default = 0, choices = ENHANCEMENT_VALUE_CHOICES)
	notes = models.CharField('Additional notes', max_length = 2000, blank = True)

	def get_absolute_url(self):
		return reverse('applicationDetail', kwargs = {'applicationID': self.pk})

	def __str__(self):
		return self.name

robotdb/models/Article.py
from django.db import models
from django.urls import reverse

class Article(models.Model):
	name = models.CharField(max_length = 100, unique = True)
	link = models.CharField('Link to article', max_length = 400, blank = True)
	year = models.PositiveSmallIntegerField(default = 0)
	bibtex = models.CharField(max_length = 2000, blank = True)
	notes = models.CharField('Additional notes', max_length = 2000, blank = True)

	def get_absolute_url(self):
		return reverse('articleDetail', kwargs = {'articleID': self.pk})

	def __str__(self):
		name = self.name
		if (len(name) > 33):
			name = name[:30] + '...'
		return name + ' (' + str(self.year) + ')'

robotdb/models/RobotImage.py
import os
from django.db import models
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFit

from .Robot import Robot
from .utils import getRobotImagePath

class RobotImage(models.Model):
	robot = models.ForeignKey(Robot, on_delete = models.CASCADE)
	image = models.ImageField(upload_to = getRobotImagePath, height_field = 'height', width_field = 'width', unique = True)
	thumbnail = ImageSpecField(source = 'image', processors = [ResizeToFit(200, 200)], format = 'JPEG', options = {'quality': 90})
	description = models.CharField('Image description', max_length = 200, blank = True)
	height = models.PositiveIntegerField('Image height', blank = True)
	width = models.PositiveIntegerField('Image width', blank = True)

	def __str__(self):
		name = self.robot.name
		if (self.description):
			name += ':' + self.description
		else:
			name += ':' + os.path.basename(self.image.file.name)
		return name

robotdb/models/utils.py
import os

def getRobotImagePath(instance, filename):
	return os.path.join('robotPhotos', str(instance.robot.id), filename)

robotdb/views.py
from django.shortcuts import render
from django_tables2 import RequestConfig

from .models import Application, Article, Feature, Project, Robot
from .tables import ApplicationTable, ArticleTable, FeatureTable, ProjectTable, RobotTable

def index(request):
	return render(request, 'index.html')

def applicationList(request):
	applications = Application.objects.all()
	applicationTable = ApplicationTable(applications)
	RequestConfig(request).configure(applicationTable)
	return render(request, 'applicationList.html', {
		'count': len(applications),
		'applicationTable': applicationTable,
	})

def applicationDetail(request, applicationID):
	return render(request, 'applicationDetails.html', {
		'application': Application.objects.get(id = applicationID)
	})

def articleList(request):
	articles = Article.objects.all()
	articleTable = ArticleTable(articles)
	RequestConfig(request).configure(articleTable)
	return render(request, 'articleList.html', {
		'count': len(articles),
		'articleTable': articleTable,
	})

def articleDetail(request, articleID):
	return render(request, 'articleDetails.html', {
		'article': Article.objects.get(id = articleID)
	})

def featureList(request):
	features = Feature.objects.all()
	featureTable = FeatureTable(features)
	RequestConfig(request).configure(featureTable)
	return render(request, 'featureList.html', {
		'count': len(features),
		'featureTable': featureTable,
	})

def featureDetail(request, featureID):
	return render(request, 'featureDetails.html', {
		'feature': Feature.objects.get(id = featureID)
	})

def projectList(request):
	projects = Project.objects.all()
	projectTable = ProjectTable(projects)
	RequestConfig(request).configure(projectTable)
	return render(request, 'projectList.html', {
		'count': len(projects),
		'projectTable': projectTable,
	})

def projectDetail(request, projectID):
	return render(request, 'projectDetails.html', {
		'project': Project.objects.get(id = projectID)
	})

def robotList(request):
	robots = Robot.objects.all()
	robotTable = RobotTable(robots)
	RequestConfig(request).configure(robotTable)
	return render(request, 'robotList.html', {
		'count': len(robots),
		'robotTable': robotTable,
	})

def robotDetail(request, robotID):
	return render(request, 'robotDetails.html', {
		'robot': Robot.objects.get(id = robotID)
	})

robotdb/views/articleViews.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from django.forms import widgets
from django.urls import reverse

from django_tables2 import RequestConfig
from django_tables2.views import SingleTableMixin
from django_filters.views import FilterView

from robotdb.models import Article
from robotdb.tables import ArticleTable

class ArticleCreateView(LoginRequiredMixin, CreateView):
	model = Article
	template_name = 'views/article/create.html'
	fields = (
		'name',
		'link',
		'year',
		'bibtex',
		'notes',
	)

	def get_form(self, **kwargs):
		form = super(ArticleCreateView, self).get_form(**kwargs)
		form.fields['bibtex'].widget = widgets.Textarea()
		form.fields['notes'].widget = widgets.Textarea()
		return form

class ArticleDetailView(LoginRequiredMixin, DetailView):
	model = Article
	template_name = 'views/article/detail.html'
	context_object_name = 'article'
	pk_url_kwarg = 'articleID'

class ArticleUpdateView(LoginRequiredMixin, UpdateView):
	model = Article
	template_name = 'views/article/update.html'
	pk_url_kwarg = 'articleID'

	fields = (
		'name',
		'link',
		'year',
		'bibtex',
		'notes',
	)

	def get_form(self, **kwargs):
		form = super(ArticleUpdateView, self).get_form(**kwargs)
		form.fields['bibtex'].widget = widgets.Textarea()
		form.fields['notes'].widget = widgets.Textarea()
		return form

# class ArticleListView(LoginRequiredMixin, SingleTableMixin, FilterView):
class ArticleListView(LoginRequiredMixin, SingleTableMixin, ListView):
	model = Article
	template_name = 'views/list.html'

	table_class = ArticleTable
	paginate_by = False
	table_pagination = False
	# filterset_class = ArticleFilter

	def get_context_data(self, **kwargs):
		context = super(ArticleListView, self).get_context_data(**kwargs)

		context['title'] = 'Articles'
		context['addButton'] = {
			'url': reverse('articleCreate'),
			'title': 'Add an article',
		}

		return context

	def get_table_pagination(self, table):
		return False

robotdb/views/equipmentViews.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from django.forms import widgets
from django.urls import reverse

from django_tables2.views import SingleTableMixin
# from django_filters.views import FilterView

from robotdb.models import Equipment
from robotdb.tables import EquipmentTable

class EquipmentCreateView(LoginRequiredMixin, CreateView):
	model = Equipment
	template_name = 'views/equipment/create.html'
	fields = (
		'name',
		'parameters',
		'notes',
	)

	def get_form(self, **kwargs):
		form = super(EquipmentCreateView, self).get_form(**kwargs)
		form.fields['notes'].widget = widgets.Textarea()
		return form

class EquipmentDetailView(LoginRequiredMixin, DetailView):
	model = Equipment
	template_name = 'views/equipment/detail.html'
	context_object_name = 'equipment'
	pk_url_kwarg = 'equipmentID'

class EquipmentUpdateView(LoginRequiredMixin, UpdateView):
	model = Equipment
	template_name = 'views/equipment/update.html'
	pk_url_kwarg = 'equipmentID'

	fields = (
		'name',
		'parameters',
		'notes',
	)

	def get_form(self, **kwargs):
		form = super(EquipmentUpdateView, self).get_form(**kwargs)
		form.fields['notes'].widget = widgets.Textarea()
		return form

# class EquipmentListView(LoginRequiredMixin, SingleTableMixin, FilterView):
class EquipmentListView(LoginRequiredMixin, SingleTableMixin, ListView):
	model = Equipment
	template_name = 'views/list.html'

	table_class = EquipmentTable
	paginate_by = False
	table_pagination = False
	# filterset_class = EquipmentFilter

	def get_context_data(self, **kwargs):
		context = super(EquipmentListView, self).get_context_data(**kwargs)

		context['title'] = 'Equipments'
		context['addButton'] = {
			'url': reverse('equipmentCreate'),
			'title': 'Add an equipment',
		}

		return context

	def get_table_pagination(self, table):
		return False

robotdb/views/projectViews.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from django.forms import widgets
from django.urls import reverse

# from django_tables2 import RequestConfig
from django_tables2.views import SingleTableMixin
# from django_filters.views import FilterView

from robotdb.models import Project
from robotdb.tables import ProjectTable

class ProjectCreateView(LoginRequiredMixin, CreateView):
	model = Project
	template_name = 'views/project/create.html'
	fields = (
		'name',
		'link',
		'yearStart',
		'yearEnd',
		'notes',
	)

	def get_form(self, **kwargs):
		form = super(ProjectCreateView, self).get_form(**kwargs)
		form.fields['notes'].widget = widgets.Textarea()
		return form

class ProjectDetailView(LoginRequiredMixin, DetailView):
	model = Project
	template_name = 'views/project/detail.html'
	context_object_name = 'project'
	pk_url_kwarg = 'projectID'

class ProjectUpdateView(LoginRequiredMixin, UpdateView):
	model = Project
	template_name = 'views/project/update.html'
	pk_url_kwarg = 'projectID'

	fields = (
		'name',
		'link',
		'yearStart',
		'yearEnd',
		'notes',
	)

	def get_form(self, **kwargs):
		form = super(ProjectUpdateView, self).get_form(**kwargs)
		form.fields['notes'].widget = widgets.Textarea()
		return form

# class ProjectListView(LoginRequiredMixin, SingleTableMixin, FilterView):
class ProjectListView(LoginRequiredMixin, SingleTableMixin, ListView):
	model = Project
	template_name = 'views/list.html'

	table_class = ProjectTable
	paginate_by = False
	table_pagination = False
	# filterset_class = ProjectFilter

	def get_context_data(self, **kwargs):
		context = super(ProjectListView, self).get_context_data(**kwargs)

		context['title'] = 'Projects'
		context['addButton'] = {
			'url': reverse('projectCreate'),
			'title': 'Add a project',
		}

		return context

	def get_table_pagination(self, table):
		return False

robotdb/views/robotViews.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from django.forms import widgets
from django.urls import reverse

from django_tables2.views import SingleTableMixin
from django_filters.views import FilterView

from robotdb.models import Robot
from robotdb.tables import RobotTable
from robotdb.filters import RobotFilter

class RobotCreateView(LoginRequiredMixin, CreateView):
	model = Robot
	template_name = 'views/robot/create.html'
	fields = (
		'name',
		'producer',
		'country',
		'year',
		'link',
		'videoLink',
		'price',
		'notes',
	)

	def get_form(self, **kwargs):
		form = super(RobotCreateView, self).get_form(**kwargs)
		form.fields['videoLink'].widget = widgets.Textarea()
		form.fields['notes'].widget = widgets.Textarea()
		return form

class RobotDetailView(LoginRequiredMixin, DetailView):
	model = Robot
	template_name = 'views/robot/detail.html'
	context_object_name = 'robot'
	pk_url_kwarg = 'robotID'

	def get_context_data(self, **kwargs):
		context = super(RobotDetailView, self).get_context_data(**kwargs)
		links = context['robot'].videoLink.split('\n')
		if len(links) > 1:
			context['robot'].videoLinks = context['robot'].videoLink.split('\n')
		return context

class RobotUpdateView(LoginRequiredMixin, UpdateView):
	model = Robot
	template_name = 'views/robot/update.html'
	pk_url_kwarg = 'robotID'

	fields = (
		'name',
		'producer',
		'country',
		'year',
		'link',
		'videoLink',
		'price',
		'notes',
	)

	def get_form(self, **kwargs):
		form = super(RobotUpdateView, self).get_form(**kwargs)
		form.fields['videoLink'].widget = widgets.Textarea()
		form.fields['notes'].widget = widgets.Textarea()
		return form

class RobotListView(LoginRequiredMixin, SingleTableMixin, FilterView):
	model = Robot
	template_name = 'views/list.html'

	table_class = RobotTable
	paginate_by = False
	table_pagination = False
	filterset_class = RobotFilter

	def get_filterset_kwargs(self, filterset_class):
		kwargs = super(RobotListView, self).get_filterset_kwargs(filterset_class)
		if kwargs['data'] is None:
			kwargs['data'] = {}
		return kwargs

	def get_context_data(self, **kwargs):
		context = super(RobotListView, self).get_context_data(**kwargs)
		context['title'] = 'Robots'
		context['addButton'] = {
			'url': reverse('robotCreate'),
			'title': 'Add a robot',
		}
		return context

	def get_table_pagination(self, table):
		return False

robotdb/views/skillViews.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from django.forms import widgets
from django.urls import reverse

from django_tables2.views import SingleTableMixin
# from django_filters.views import FilterView

from robotdb.models import Skill
from robotdb.tables import SkillTable

class SkillCreateView(LoginRequiredMixin, CreateView):
	model = Skill
	template_name = 'views/skill/create.html'
	fields = (
		'name',
		'mobility',
		'selfreliantCare',
		'interpersonalInteraction',
		'other',
		'notes',
	)

	def get_form(self, **kwargs):
		form = super(SkillCreateView, self).get_form(**kwargs)
		form.fields['notes'].widget = widgets.Textarea()
		return form

class SkillDetailView(LoginRequiredMixin, DetailView):
	model = Skill
	template_name = 'views/skill/detail.html'
	context_object_name = 'skill'
	pk_url_kwarg = 'skillID'

class SkillUpdateView(LoginRequiredMixin, UpdateView):
	model = Skill
	template_name = 'views/skill/update.html'
	pk_url_kwarg = 'skillID'

	fields = (
		'name',
		'mobility',
		'selfreliantCare',
		'interpersonalInteraction',
		'other',
		'notes',
	)

	def get_form(self, **kwargs):
		form = super(SkillUpdateView, self).get_form(**kwargs)
		form.fields['notes'].widget = widgets.Textarea()
		return form

# class SkillListView(LoginRequiredMixin, SingleTableMixin, FilterView):
class SkillListView(LoginRequiredMixin, SingleTableMixin, ListView):
	model = Skill
	template_name = 'views/list.html'

	table_class = SkillTable
	paginate_by = False
	table_pagination = False
	# filterset_class = SkillFilter

	def get_context_data(self, **kwargs):
		context = super(SkillListView, self).get_context_data(**kwargs)

		context['title'] = 'Skills'
		context['addButton'] = {
			'url': reverse('skillCreate'),
			'title': 'Add a skill',
		}

		return context

	def get_table_pagination(self, table):
		return False

robotdb/templates/views/robot/create.html
{% extends "base.html" %}

{% block title %}
	<h1>Adding a robot</h1>
{% endblock %}

{% block topMenu %}
<a href="{% url 'robotList' %}" class="button">Back to List</a>
{% endblock %}

{% block content %}
	<form class="entryEditForm" action="{% url 'robotCreate' %}" method="post">
		{% csrf_token %}
		<h3>Robot properties:</h3>
		<table class="pure-table entryDetails entryEditTable">
			{{ form.as_table }}
		</table>

		<div class="formSubmitButton">
			<input type="submit" value="Save" class="button" />
		</div>
	</form>
{% endblock %}

robotdb/templates/views/robot/detail.html
{% extends "base.html" %}

{% block title %}
	<h1>Robot details</h1>
{% endblock %}

{% block topMenu %}
<a href="{% url 'robotList' %}" class="button">Back to List</a>
<a href="{% url 'robotUpdate' robot.id %}" class="button">Edit this robot</a>
<a href="{% url 'robotCreate' %}" class="button">Add another</a>
{% endblock %}

{% block content %}
	<h3>Robot properties:</h3>
	<table class="pure-table entryDetails">
		<tr>
			<th>Name</th>
			<td>{{ robot.name }}</td>
		</tr>
		<tr>
			<th>Producer</th>
			<td>{{ robot.producer }}</a></td>
		</tr>
		<tr>
			<th>Country</th>
			<td>{{ robot.country }}</a></td>
		</tr>
		<tr>
			<th>Year</th>
			<td>{{ robot.year }}</a></td>
		</tr>
		<tr>
			<th>Link</th>
			<td>{% if robot.link %}<a href="{{ robot.link }}">{{ robot.link }}</a>{% endif %}</td>
		</tr>
		<tr>
			<th>Link to a video</th>
			<td>
				{% if robot.videoLinks %}
					<ul>
					{% for link in robot.videoLinks %}
						<li><a href="{{ link }}">{{ link }}</a></li>
					{% endfor %}
					</ul>
				{% elif robot.videoLink %}
					<a href="{{ robot.videoLink }}">{{ robot.videoLink }}</a>
				{% endif %}
			</td>
		</tr>
		<tr>
			<th>Notes</th>
			<td>{{ robot.notes }}</a></td>
		</tr>
		<tr>
			<th>Price</th>
			<td>{{ robot.price }}</a></td>
		</tr>
	</table>

	<h3>Articles:</h3>
	<table class="pure-table featureList">
		<thead><tr>
			<th>Name</th>
			<th>Year</th>
			<th>Link</th>
		</tr></thead>
		<tbody>
			{% for art in robot.articles.all %}
			<tr>
				<td><a href="{% url 'articleDetail' art.pk %}">{{ art.name }}</a></td>
				<td>{{ art.year }}</td>
				<td>{% if art.link %}<a href="art.link">{{ art.link }}</a>{% endif %}</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>

	<h3>Projects:</h3>
	<table class="pure-table featureList">
		<thead><tr>
			<th>Name</th>
			<th>Year</th>
			<th>Link</th>
		</tr></thead>
		<tbody>
			{% for project in robot.projects.all %}
			<tr>
				<td><a href="{% url 'articleDetail' project.pk %}">{{ project.name }}</a></td>
				<td>{{ project.year }}</td>
				<td>{% if project.link %}<a href="project.link">{{ project.link }}</a>{% endif %}</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>

	<h3>Skills:</h3>
	<table class="pure-table featureList">
		<thead><tr>
			<th>Name</th>
			<th>Mobility enhancement</th>
			<th>Selfreliant care</th>
			<th>Interpersonal interaction</th>
			<th>Other</th>
			<th>Notes</th>
		</tr></thead>
		<tbody>
			{% for skill in robot.skills.all %}
			<tr>
				<td><a href="{% url 'skillDetail' skill.pk %}">{{ skill.name }}</a></td>
				<td>{{ skill.get_mobility_display }}</td>
				<td>{{ skill.get_selfreliantCare_display }}</td>
				<td>{{ skill.get_interpersonalInteraction_display }}</td>
				<td>{{ skill.get_other_display }}</td>
				<td>{{ skill.notes }}</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>

	<h3>Equipment:</h3>
	<table class="pure-table featureList">
		<thead><tr>
			<th>Name</th>
			<th>Parameters</th>
			<th>Notes</th>
		</tr></thead>
		<tbody>
			{% for eq in robot.equipment.all %}
			<tr>
				<td><a href="{% url 'equipmentDetail' eq.pk %}">{{ eq.name }}</a></td>
				<td>{{ eq.parameters }}</td>
				<td>{{ eq.notes }}</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>

	<h3>Photos:</h3>
	<div class="robotPhotos">
		<ul class="robotImageList">
			{% for robotImage in robot.robotimage_set.all %}
				<li><a href="{{ robotImage.image.url }}">
					<img src="{{ robotImage.thumbnail.url }}" />
				</a></li>
			{% endfor %}
		</ul>
	</div>
{% endblock %}

robotdb/templates/views/robot/update.html
{% extends "base.html" %}

{% block title %}
	<h1>Editing a robot</h1>
{% endblock %}

{% block topMenu %}
<a href="{% url 'robotDetail' robot.id %}" class="button">Back to details</a>
<a href="{% url 'robotList' %}" class="button">Back to List</a>
<a href="{% url 'admin:robotdb_robot_change' robot.id %}" class="button">Advanced edit (Equipment, Skills, Photos etc)</a>
{% endblock %}

{% block content %}
	<form class="entryEditForm" action="{% url 'robotUpdate' robot.id %}" method="post">
		{% csrf_token %}
		<h3>Robot properties:</h3>

		<table class="pure-table entryDetails entryEditTable">
			{{ form.as_table }}
		</table>

		<div class="formSubmitButton">
			<input type="submit" value="Save" class="button" />
		</div>
	</form>
{% endblock %}